name: Update Viot staging docker images

on:
  push:
    branches:
      - main
    paths:
      - "viot/**"
      - ".github/workflows/viot-staging.yml"
      - "docker/viot/**"
      - "docker-compose.yml"
jobs:
  update_staging:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push Viot API docker image staging to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/viot/viot.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/viot/api:staging

      - name: Push Viot Celery docker image staging to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/viot-celery/celery.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/viot/celery:staging
